import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";

const jost = Jost({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-jost",
});
export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${jost.variable} bg-custom-pattern bg-center h-screen w-screen bg-no-repeat bg-[#F7FCFA]`}
      >
        {children}
      </body>
    </html>
  );
}
